// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
// Anon key: accept either VITE_SUPABASE_ANON_KEY or VITE_SUPABASE_PUBLISHABLE_KEY (same value)
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";

const isValidUrl = (s: string) => s && (s.startsWith("http://") || s.startsWith("https://"));
const isConfigured = isValidUrl(SUPABASE_URL) && !!SUPABASE_ANON_KEY;

let _supabase: SupabaseClient<Database> | null = null;

function getSupabase(): SupabaseClient<Database> {
  if (_supabase) return _supabase;
  if (!isConfigured) {
    // Return a no-op client so the app loads without Supabase. Auth and Edge Functions will no-op or return errors.
    return createNoOpClient();
  }
  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
  return _supabase;
}

const NOT_CONFIGURED_MSG = "Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY (or VITE_SUPABASE_PUBLISHABLE_KEY) to .env — see .env.example.";

function createNoOpClient(): SupabaseClient<Database> {
  const noOpAuth = {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: (_callback: () => void) => ({
      data: { subscription: { unsubscribe: () => {} } },
    }),
    signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: NOT_CONFIGURED_MSG } }),
    signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: NOT_CONFIGURED_MSG } }),
    signOut: () => Promise.resolve({ error: null }),
  };
  const noOpFunctions = {
    invoke: (_name: string, _options?: unknown) =>
      Promise.resolve({ data: null, error: { message: NOT_CONFIGURED_MSG } }),
  };
  return { auth: noOpAuth, functions: noOpFunctions } as unknown as SupabaseClient<Database>;
}

export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop) {
    return getSupabase()[prop as keyof SupabaseClient<Database>];
  },
});